Tidy the code, better commenting when things go wrong

diff --git a/.github/workflows/merge_upstream_master.yml b/.github/workflows/merge_upstream_master.yml
--- a/.github/workflows/merge_upstream_master.yml
+++ b/.github/workflows/merge_upstream_master.yml
@@ -16,18 +16,20 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - id: create_token
-        uses: tibdex/github-app-token@v2
+        uses: actions/create-github-app-token@v1
         with:
-          app_id: ${{ secrets.APP_ID }}
-          private_key: ${{ secrets.PRIVATE_KEY }}
+          app-id: ${{ secrets.APP_ID }}
+          private-key: ${{ secrets.PRIVATE_KEY }}
+
+      - run: echo "GH_TOKEN=${{ steps.create_token.outputs.token }}" >> "$GITHUB_ENV"
 
       - name: PR Data
-        env:
-          GH_TOKEN: ${{ steps.create_token.outputs.token }}
         run: |
+          echo "FAIL_NOTIFIED=true" >> $GITHUB_ENV
           pr_json=$(curl -L -s --fail-with-body -H "Authorization: token ${{ github.token }}" ${{ github.event.issue.pull_request.url }})
           if [ `jq -r '.maintainer_can_modify' <<<$pr_json` == "false" ] ; then
             gh pr comment ${{ github.event.issue.html_url }} --body 'GitHub Actions can not push to the repository without "Allow edits and access to secrets by maintainers" checked.'
+            echo "FAIL_NOTIFIED=true" >> $GITHUB_ENV
             exit 1
           fi
           echo "PR_REPO=`jq -r '.head.repo.full_name' <<<$pr_json`" >> $GITHUB_ENV
@@ -35,24 +37,18 @@ jobs:
           echo "PR_HEAD_LABEL=`jq -r '.head.label' <<<$pr_json`" >> $GITHUB_ENV
 
       - uses: actions/checkout@v4
-        env:
-          GH_TOKEN: ${{ steps.create_token.outputs.token }}
         with:
           repository: ${{ env.PR_REPO }}
           ref: ${{ env.PR_BRANCH }}
-          token: ${{ steps.create_token.outputs.token }}
+          token: ${{ env.GH_TOKEN }}
 
       - uses: actions/setup-node@v4
-        env:
-          GH_TOKEN: ${{ steps.create_token.outputs.token }}
         with:
           node-version: 20
           cache: 'yarn'
           cache-dependency-path: ./tgui/yarn.lock
 
       - uses: actions/setup-python@v5
-        env:
-          GH_TOKEN: ${{ steps.create_token.outputs.token }}
         with:
           python-version: '3.11'
           cache: 'pip'
@@ -61,7 +57,6 @@ jobs:
         env:
           BASE_BRANCH: ${{ github.event.repository.default_branch }}
           BASE_REPOSITORY: ${{ github.repository }}
-          GH_TOKEN: ${{ steps.create_token.outputs.token }}
         run: |
           # Compare head branch and base branch
           compare_result=$(curl -L -s --fail-with-body \
@@ -93,11 +88,19 @@ jobs:
 
           git fetch origin "$PR_BRANCH" --depth=$((ahead_by + 1))
           git fetch upstream "$BASE_BRANCH" --depth=$((behind_by + 1))
+
+          # Check if a workflow file would be modified by the merge
+          latest_workflow_commit=$(git log -n 1 --pretty=format:"%H" upstream/$BASE_BRANCH -- .github/workflows)
+          if ! git branch --contains $latest_workflow_commit | grep -q "$(git rev-parse --abbrev-ref HEAD)"; then
+            gh pr comment ${{ github.event.issue.html_url }} --body "GitHub Actions can not push to this branch as it would modify a workflow file, please update your branch past https://github.com/ParadiseSS13/Paradise/commit/$latest_workflow_commit before using this command again."
+            echo "FAIL_NOTIFIED=true" >> $GITHUB_ENV
+            exit 1
+          fi
+
           git merge FETCH_HEAD
           git push origin
 
       - name: Notify Failure
-        if: failure()
-        env:
-          GH_TOKEN: ${{ steps.create_token.outputs.token }}
-        run: gh pr comment ${{ github.event.issue.html_url }} -b "Merging upstream failed:\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+        if: failure() && ${{ !env.FAIL_NOTIFIED == 'true' }}
+        run: |
+          gh pr comment ${{ github.event.issue.html_url }} -b "Merging upstream failed, see the action run log for details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
